install.packages('parallel')
install.packages('doParallel')
install.packages('foreach')
install.packages('ncdf4')
install.packages('SPEI')
install.packages('qmap')
install.packages('sf')
install.packages('ranger')

library(parallel)
library(doParallel)
library(foreach)
library(ncdf4)
library(SPEI)
library(qmap)
library(sf)
