#SPEI forecast ensemble members - automatically!

#Generates SPEI values for a probabilistic forecast (one month, 1 members). Consumes the fitting parameters generated by running SPEI_UnbiasedGrid on the historical gridded data. This allows this script to calculate only the outputs rather than having to fit the log-logistic functions.

if(!require(SPEI)){
  install.packages('SPEI')
}
if(!require(doParallel)){
  install.packages('doParallel')
}
if(!require(foreach)){
  install.packages('foreach')
}

library(SPEI)
library(parallel)
library(doParallel)
library(foreach)

elapsed_months <- function(end_date, start_date) {        #Thank you, pbnelson from stackoverflow
  ed <- as.POSIXlt(end_date)
  sd <- as.POSIXlt(start_date)
  12 * (ed$year - sd$year) + (ed$mon - sd$mon)
}

#Arguments from the command line. Can be entered manually from here if desired. Controls dates and the main directory.

FirstMonth = as.Date('2018-01-01')
ForecastDate = as.Date(commandArgs(trailingOnly = TRUE)[2])
LastDate = as.Date(commandArgs(trailingOnly = TRUE)[3])

#Finding the month and year as numeric values
ForecastMonthInt = as.integer(format(LastDate, format="%m"))
LastYear = as.integer(format(LastDate, format="%Y"))

MainDir = paste0(commandArgs(trailingOnly = TRUE)[4], '\\')

MonthCount = elapsed_months(LastDate, FirstMonth) + 1

#Where the calibrated fitting values are stored
CalFilesDir = paste0(MainDir, 'Misc\\SPEICal\\')

CalFiles = list.files(CalFilesDir)
CalLocNum = length(CalFiles)/12           #Since there's a file with 1 month, 2 month, ..., 12 month calibrations, we have 12 times as many files as points

CalLocFiles = CalFiles[(1:CalLocNum) * 12]

for(i in 1:length(CalLocFiles)){
  CalLocFiles[i] = paste(unlist(strsplit(CalLocFiles[i], '_'))[1], unlist(strsplit(CalLocFiles[i], '_'))[2], sep='_')
}


Calibrations = array(0, c(3,12,CalLocNum,12))   #constant, month, location, months*

#months meaning like a 1 or 2 or 3 month SPEI, as opposed to month meaning Jan, Feb, March, ...

#Read in all calibrations before starting to do SPEI

j = 1
for(File in CalLocFiles){
  
  for(i in 1:12){
    
    FilePath = paste0(CalFilesDir, File, "_", i, '.csv')
    CalData = read.csv(FilePath)
    
    for(x in 1:3){
      for(y in 1:12){
        
        Calibrations[x,y,j,i] = CalData[x,y+1]
        
      }
    }
    
  }
  j = j+1
}

#Calibrations are set - proceed with SPEI generation

InDir = paste0(MainDir, 'Indices\\PDI\\', ForecastDate, '\\SPEI Input\\')
OutDir = paste0(MainDir, 'Indices\\SPEI\\', ForecastDate, '\\')
dir.create(OutDir)


FirstMemDir = paste0(InDir, '0\\')
AllFiles = list.files(FirstMemDir)


for(Mem in 0:0){   #Run a core for each of the members - each core will hit each location, which will result in 1 sets of SPEI
  library(SPEI)
  
  
  InMemDir = paste0(InDir, Mem, '\\')     #Directories...
  OutMemDir = paste0(OutDir, Mem, '\\')
  
  dir.create(paste0(OutDir, Mem, '\\'))
  
  for(Loc in 1:length(AllFiles)){         #Now go through each file. Read in P-PE, generate a time series variable, take the appropriate calibration, and 
    File = AllFiles[Loc]                  #generate SPEI.
    InFile = paste(InMemDir, File,sep='')
    OutFile = paste(OutMemDir, File,sep='')
    
    if(!file.exists(InFile)) next
    
    InData = read.table(InFile, sep = ",", header=TRUE)
    InVec = as.vector(InData[,3])
    
    TimeSers = ts(InVec, start = c(2018,1), end=c(LastYear,ForecastMonthInt), frequency=12)		#A time series running from start of grid to end of forecast, monthly intervals
    
    SPEIOut = array(-99.99, c(MonthCount, 2 + 12))  #1950 to Aug 2018 is 824 months, 1950 to Dec 2015 is 792 months - Year + Month + SPEI for 12 months
    
    if(File == AllFiles[1]){  
      SPEIFalse = spei(TimeSers, 1, x=TRUE) #If it's the first run, do a dummy SPEI to generate the calibration format
      Calibration = SPEIFalse$coefficients
    }
    
    #As a note, calibrations are formatted very strangely, likely for good reason, but strangely. They are structured [1:3, 1, 1:12] where index 1 is xi, alpha, or kappa, index 2 is meaningless, and index 3 is the month.
    
    
    i=0
    for(Year in 2018:LastYear){     #Go through all years, making sure not to hit months in the future.
      
      TopMonth = 12
      if(Year == LastYear) TopMonth = ForecastMonthInt
      for(Month in 1:TopMonth){
        
        i=i+1
        SPEIOut[i,1] = Year
        SPEIOut[i,2] = Month
        
      }
    }
    
    for(j in 1:12){
      
      Calibration[,1,] = Calibrations[,,Loc,j]
      
      SPEI = spei(TimeSers, j, x=TRUE, params = Calibration)
      SPEIOut[,j+2] = SPEI$fitted
    }
    
    colnames(SPEIOut) = c('Year', 'Month', 'SPEI1', 'SPEI2', 'SPEI3', 'SPEI4', 'SPEI5', 'SPEI6', 'SPEI7', 'SPEI8', 'SPEI9', 'SPEI10', 'SPEI11', 'SPEI12')
    write.table(SPEIOut, OutFile, quote=FALSE, sep=',', row.names = FALSE)					#spei generates an spei object - [2] is the matrix of values
    
  }
}
